name: LimitCrafting
main: me.tezk.limitcrafting.LimitCraftingPlugin
version: 4.1
author: Tom Micallef
description: Limit players from crafting items.

commands:
  limitcrafting:
    description: LimitCrafting reload command
    usage: /<command>

permissions:
  limitcrafting.bypass:
    default: op
  limitcrafting.reload:
    default: op